SUB MAIN
  PRINT "---- SINE, COSINE, TANGENTS (HYPERBOLIC) ----"

  PRINT "COSH(1) = " + STRING(COSH(1))
  PRINT "SINH(1) = " + STRING(SINH(1))
  PRINT "TANH(1) = " + STRING(TANH(1))

  PRINT "ACOSH(1.543) = " + STRING(ACOSH(1.543))
  PRINT "ASINH(1.175) = " + STRING(ASINH(1.175))
  PRINT "ATANH(0.762) = " + STRING(ATANH(0.762))

  PRINT "\n---- SECANT, COSECANT, COTANGENT (HYPERBOLIC) ----"

  PRINT "SECH(1) = " + STRING(SECH(1))
  PRINT "CSCH(1) = " + STRING(CSCH(1))
  PRINT "COTH(1) = " + STRING(COTH(1))

  PRINT "ASECH(0.648) = " + STRING(ASECH(0.648))
  PRINT "ACSCH(0.851) = " + STRING(ACSCH(0.851))
  PRINT "ACOTH(1.313) = " + STRING(ACOTH(1.313))
END SUB
