#include "maplib.bas"

SUB MAIN

	DIM C AS BOOLEAN
	DIM D AS DOUBLE
	DIM I AS INTEGER

	REM IF YOU WANT TO TRY FUNCTION
	REM CONSTRAINT(),
	REM ENABLE THIS OPTION
	C = FALSE

	D = MAPINT(249,0,360,0,100,C)
	I = MAPINT(249,0,360,0,100,C)

	PRINT "WITHOUT ANY DECLARING: " + STR$(MAPINT(249, 0,360, 0,100, FALSE))
PRINT ""

	PRINT "DECLARED AS DOUBLE: " + STR$(D)
PRINT ""

	PRINT "DECLARED AS INTEGER: " + STR$(I)
PRINT ""

END SUB
