REM RECEIVE DATA FROM
REM REMOTE SERVER USING
REM GET REQUEST
FUNCTION REQUEST(ADDRESS AS STRING) AS STRING
	DIM RESPONSE AS STRING
	OPEN #1,ADDRESS,"r"
	READLINE #1,RESPONSE
	CLOSE #1
	REQUEST = RESPONSE
END FUNCTION
