SUB PASS_ARRAY_1D(ARRAY(3) AS INTEGER)
  DIM I AS INTEGER
  FOR I=1 TO 3
    PRINT "PASS_ARRAY_1D> ARRAY(" + STRING(I) + ")=" + STRING(ARRAY(I))
  END FOR
END SUB

SUB PASS_ARRAY_2D(ARRAY(3,3) AS INTEGER)
  DIM I,J AS INTEGER
  FOR I=1 TO 3
    FOR J=1 TO 3
      PRINT "PASS_ARRAY_2D> ARRAY(" + STRING(I) + "," + STRING(J) + ")=" + STRING(ARRAY(I,J))
    END FOR
  END FOR
END SUB

SUB MAIN
  DIM ARRAY1(3) AS INTEGER
  DIM ARRAY2(3,3) AS INTEGER
  DIM I,J AS INTEGER
  
  FOR I=1 TO 3
    ARRAY1(I) = I
    FOR J=1 TO 3
      ARRAY2(I,J) = (I-1) * 3 + J
    END FOR
  END FOR
  
  CALL PASS_ARRAY_1D(ARRAY1)
  CALL PASS_ARRAY_2D(ARRAY2)
END SUB
