SUB MAIN
  DIM TM AS DOUBLE
  DIM DD,MM,CCYY AS INTEGER
  DIM HRS,MINS,SECS,MILLI AS INTEGER
  TM=NOW()
  DD=DAY(TM)
  MM=MONTH(TM)
  CCYY=YEAR(TM)
  HRS=HOUR(TM)
  MINS=MINUTE(TM)
  SECS=SECOND(TM)
  MILLI=MILLISECOND(TM)
  PRINT "Todays Date (DD/MM/CCYY) = " + STRING(DD) + "/" + STRING(MM) + "/" + STRING(CCYY)
  PRINT "Current Time = " + STRING(HRS) + ":" + STRING(MINS) + ":" + STRING(SECS) + "." + STRING(MILLI)
END SUB