SUB MAIN
  DIM HEIGHT, WIDTH AS INTEGER
  DIM I AS INTEGER
  
  GRAPHICS

  HEIGHT=SCREENHEIGHT()
  WIDTH=SCREENWIDTH()

  SETCOLOR 0,0,0	// BLACK
  CLS

  SETCOLOR 255,255,0	// YELLOW
  FOR I=0 to WIDTH STEP 5
    PRINT "I=" + STR$(I)
    DRAWLINE 0,0,I,HEIGHT
  END FOR
  
  SETCOLOR 0,255,255	// CYAN
  FOR I=0 TO WIDTH STEP 5
    DRAWLINE WIDTH,0,I,HEIGHT
  END FOR

  REPAINT

  FOR I=1 TO 10
    SLEEP 1000
    TEXT
    SLEEP 1000
    GRAPHICS
  END FOR
END SUB