SUB MAIN
  DIM ALPHABET AS STRING
  DIM XPOS, YPOS AS INTEGER
  
  ALPHABET="ABCDEFGHIJKLMNOPQRSTUVWXYZ"
  XPOS=0
  YPOS=40
  
  GRAPHICS
  SETCOLOR 0,0,0	// BLACK
  CLS

  SETCOLOR 255,255,255	// WHITE
  SETFONT "MONOSPACE", 20
  YPOS=YPOS+STRINGHEIGHT(ALPHABET)
  DRAWSTRING ALPHABET,XPOS,YPOS
  
  SETFONT "SANS_SERIF", 20
  YPOS=YPOS+STRINGHEIGHT(ALPHABET)
  DRAWSTRING ALPHABET,XPOS,YPOS
  
  SETFONT "SERIF", 20
  YPOS=YPOS+STRINGHEIGHT(ALPHABET)
  DRAWSTRING ALPHABET,XPOS,YPOS
  
  SETCOLOR 255,0,0	// RED
  SETFONT "MONOSPACE", 25
  YPOS=YPOS+STRINGHEIGHT(ALPHABET)
  DRAWSTRING ALPHABET,XPOS,YPOS
  
  SETCOLOR 0,255,0	// GREEN
  SETFONT "SANS_SERIF", 30
  YPOS=YPOS+STRINGHEIGHT(ALPHABET)
  DRAWSTRING ALPHABET,XPOS,YPOS

  ROTATE 10
  SETCOLOR 0,0,255	// BLUE
  SETFONT "SERIF", 35
  YPOS=YPOS+STRINGHEIGHT(ALPHABET)
  DRAWSTRING ALPHABET,XPOS,YPOS

  REPAINT
  
  SLEEP 5000
END SUB